version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./Country Regions:/app/Country Regions 
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}      
      - DB_USER=${DB_USER}      
      - DB_PASS=${DB_PASS}
      - CSV_PATH=${CSV_PATH}
    restart: unless-stopped

  etl:
    build: .
    container_name: etl_service
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}      
      - DB_USER=${DB_USER}      
      - DB_PASS=${DB_PASS} 
    command: python load.py  
    restart: on-failure

volumes:
  pgdata:
